// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: userPos.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Cw
{

    [global::ProtoBuf.ProtoContract()]
    public partial class UserPos : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);
        [global::ProtoBuf.ProtoMember(1)]
        public string name { get; set; }
        [global::ProtoBuf.ProtoMember(2)]
        public int MemoberIndex { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int PosX { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int PosY { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public int PoxZ { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
